### ISSUE TITLE
sector_exit value return

### ISSUE THREAD

**Issue by arunbalas** [project-bluebird/dodo#113]
The sector_exit command doesn't return any value...I would like to know if there is any issue with that?

**Comment by radka-j** [comment]
Thank you so much for trying out the code and raising this issue, this is really helpful!

The `sector_exit` metric only returns a value if the aircraft has exited the sector. If the aircraft has not exited yet (or it does not exist), the metric returns a `NaN`. This is not described in the documentation however. 

@thobson88 I wonder if it would make sense that, if an aircraft is in the sector and has not exited yet, the `sector_exit` metric returns 0 rather than `NaN`. What do you think?

**Comment by arunbalas** [comment]
Thanks @radka-j ...
- Also, regarding the metrics (loss of separation, fuel efficiency): are these values binary?, I just get zero most of the time...
- change_speed: is it ground speed? and I don't find change_vertical_speed control available..

**Comment by thobson88** [comment]
> @thobson88 I wonder if it would make sense that, if an aircraft is in the sector and has not exited yet, the sector_exit metric returns 0 rather than NaN. What do you think?

I think it's useful to be able to distinguish between the case that the exit hasn't yet happened, versus that of a perfect exit (which would presumably score 0), so I'd leave it as `NaN`.

Somewhere else we'll want to write a reward function for this metric that returns zero at every timestep except the one during which the exit took place (but I suppose that belongs in the OpenAI Gym repo?)

**Comment by radka-j** [comment]
>     * Also, regarding the metrics (loss of separation, fuel efficiency): are these values binary?, I just get zero most of the time...

All metrics are piecewise linear and bounded between 0 and -1. If you look at the aviary [metrics code](https://github.com/alan-turing-institute/aviary/tree/develop/aviary/metrics), at the top of each metric file is a description of how the score is calculated. We need to add this to the overall documentation! 

>     * change_speed: is it ground speed? and I don't find change_vertical_speed control available..

Yes `change_speed` is ground speed. We removed the `change_vertical_speed` command as it should not be used in air traffic control.

**Comment by radka-j** [comment]
@thobson88 good point, that makes sense! yes I think anything that combines the various metrics into a single score belongs in the gym repo.

**Comment by thobson88** [comment]
> - regarding the metrics (loss of separation, fuel efficiency): are these values binary?, I just get zero most of the time...

They're not binary, they both return a value in the interval [-1, 0].

In the separation metric, the score is 0 unless the two aircraft are within the "warning distance" (as defined by the `HOR_WARN_DIST` and `VER_WARN_DIST` parameters), then decreases linearly until they're within the official "loss of separation distance", at which point the metric returns -1.

Since the warning distance is pretty small, most of the time this metric will just return 0, the best score possible.

The fuel efficiency metric may also return 0 much of the time, as it only penalises aircraft that are flying lower than necessary. The exact formula is explained in `aviary/metrics/fuel_efficiency_metric.py`.

> change_speed: is it ground speed? and I don't find change_vertical_speed control available..

It's calibrated air speed (KCAS), which is the speed the pilot sees on their instruments (so any instruction must be given in this unit).

We don't support changing vertical speed because in practice the ATCO can't issue such an instruction. When they give an instruction to change altitude it's the pilot who decides how to make the manoeuvre.

**Comment by arunbalas** [comment]
Oh got it. Thank you for the clarification @radka-j  and @thobson88
